classdef MasterGUI
    
properties
    Figure
end

methods
    function obj = StartMasterGUI(obj)
        % Initialize GUI
        if isempty(obj.Figure)
            obj.Figure = figure('Name','Drink More Tap Water!');
        end
        set(obj.Figure,'Units','normalized',...
            'Position',[0.2,0.25,0.6,0.5]);
        
        Panel1 = uipanel('Parent',obj.Figure,...
                               'Units', 'normalized',...
                               'Position',[0,0,0.33,1]);
        Panel1Note = uicontrol(Panel1,...
                'Style','text',...
                'String',{['Click here to enter consumer data, load/save ',...
                'historical data, and calculate recommended values:']},...
                'Units','normalized',...
                'Position',[0.15,0.6,0.7,0.2]);
        
        
        Panel2 = uipanel('Parent',obj.Figure,...
                               'Units', 'normalized',...
                               'Position',[0.33,0,0.33,1]);
        Panel2Note = uicontrol(Panel2,...
                'Style','text',...
                'String',{['Click here to compare Bay Area water quality data, ',...
                'plot data vs FDA mandated standards, and visit external resources:']},...
                'Units','normalized',...
                'Position',[0.15,0.6,0.7,0.2]);
        
        Panel3 = uipanel('Parent',obj.Figure,...
                               'Units', 'normalized',...
                               'Position',[0.66,0,0.34,1]);
        Panel3Note = uicontrol(Panel3,...
                'Style','text',...
                'String',{['Click here to view all refill stations on campus, ',...
                'get Google Maps directions, and check open Hall hours: ']},...
                'Units','normalized',...
                'Position',[0.15,0.6,0.7,0.2]);

        Button1 = uicontrol('Parent',Panel1,...
                                 'Style','pushbutton',...
                                 'String', 'User Data',...
                                 'Units','normalized',...
                                 'Position', [.125,.3,.75,.25],...
                                 'Callback',@callback1);

        Button2 = uicontrol('Parent',Panel2,...
                                 'Style','pushbutton',...
                                 'String', 'Water Data',...
                                 'Units','normalized',...
                                 'Position', [.125,.3,.75,.25],...
                                 'Callback',@callback2);

        Button3 = uicontrol('Parent',Panel3,...
                                 'Style','pushbutton',...
                                 'String', 'Maps',...
                                 'Units','normalized',...
                                 'Position', [.125,.3,.75,.25],...
                                 'Callback',@callback3);
                             
            function callback1(hObject,eventdata)
                a = UserClassGUI();
                a.StartGUI();
            end

            function callback2(hObject,eventdata)
                obj3 = WaterDataGUI();
                obj3.StartGUI()
            end

            function callback3(hObject,eventdata)
                ui = MapDataGUI(); 
                ui.StartGUI();
            end
    end
end

end