classdef UserClassGUI < UserClass
    % Tushar Malik
    % E177 Final Project
    
    properties
        Figure
    end


    methods
        function obj = StartGUI(obj)
        % This function starts the GUI
            obj.Figure = figure('Name','User Class GUI'); 
            set(obj.Figure,'Units','normalized',...
                'Position',[0.25,0.175,0.5,0.65]);
        
        % Creating different Panels, Buttons and text boxes within the 
        % User Class GUI figure    
            Panel1 = uipanel('Parent',obj.Figure,...
                       'Units', 'normalized',...
                       'Position',[0,0,0.5,1]);

            Panel2 = uipanel('Parent',obj.Figure,...
                       'Units', 'normalized',...
                       'Position',[.5,0.5,0.5,0.5]);
                   
            Panel3 = uipanel('Parent',obj.Figure,...
                       'Units', 'normalized',...
                       'Position',[0,0,0.5,0.5]);
                   
            Panel4 = uipanel('Parent',obj.Figure,...
                       'Units', 'normalized',...
                       'Position',[0.5,0,0.5,0.5]);
                   
            NameText = uicontrol('Parent',Panel1,...
                        'Style','text',...
                        'String','Enter your Full Name',...
                        'Units','normalized',...
                        'Position',[.25,.88,.5,.1]);

            NameEdit = uicontrol('Parent',Panel1,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[.35,.88,.3,.06]);
                    
            LoadButton = uicontrol('Parent',Panel1,...
                         'Style','pushbutton',...
                         'String', 'Load Data',...
                         'Units','normalized',...
                         'Position', [0.35,0.8,.3,.06],...
                         'Callback',@Load_callback);

            HeightText = uicontrol('Parent',Panel1,...
                        'Style','text',...
                        'String','Enter your Height in meters',...
                        'Units','normalized',...
                        'Position',[.25,.65,.5,.1]);

            HeightEdit = uicontrol('Parent',Panel1,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[.38,.65,.23,.06]);

            WeightText = uicontrol('Parent',Panel1,...
                        'Style','text',...
                        'String','Enter your Weight in lbs',...
                        'Units','normalized',...
                        'Position',[.25,.52,.5,.1]);

            WeightEdit = uicontrol('Parent',Panel1,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[.38,.52,.23,.06]);
                    
            ConversionButton = uicontrol('Parent',Panel3,...
                         'Style','pushbutton',...
                         'String', 'Units Calculator',...
                         'Units','normalized',...
                         'Position', [0.25,0.82,.5,.1],...
                         'Callback',@Coversion_callback);        

            BMIsubmitButton = uicontrol('Parent',Panel3,...
                         'Style','pushbutton',...
                         'String', 'Calculate your BMI',...
                         'Units','normalized',...
                         'Position', [0.25,0.58,.5,.1],...
                         'Callback',@BMI_callback);
                     
             HistoryText = uicontrol('Parent',Panel2,...
                        'Style','text',...
                        'String','Water Consumed in Oz',...
                        'Units','normalized',...
                        'Position',[.25,.8,.5,.1]);

             HistoryEdit = uicontrol('Parent',Panel2,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[.38,.7,.23,.1]);
                    
             WCsubmitButton = uicontrol('Parent',Panel2,...
                         'Style','pushbutton',...
                         'String', 'History Of Water Consumed',...
                         'Units','normalized',...
                         'Position', [.25,.4,.5,.1],...
                         'Callback',@WC_callback);
        
        function BMI_callback(hObject,eventdata)
                He = get(HeightEdit,'String');
                W = get(WeightEdit,'String');
                B = obj.BMI(W,He);
                D = obj.Drink(W);

                BMIText = uicontrol('Parent',Panel3,...
                        'Style','text',...
                        'String','Your BMI is:',...
                        'Units','normalized',...
                        'Position',[.25,.35,.5,.1]);

                BMIEdit = uicontrol('Parent',Panel3,...
                        'Units','normalized',...
                        'Position',[.38,.3,.25,.1]);
                        set(BMIEdit, 'String', num2str(B)); 
                
                Figure2 = figure('Name','Recommendation',...
                    'Units','normalized',...
                    'OuterPosition', [0.325 0.25 0.3 0.5]);

        % Creating different Buttons and text boxes within the 
        % Recommendation GUI
                DrinkText1 = uicontrol('Parent',Figure2,...
                        'Style','text',...
                        'String','According to your Weight',...
                        'Units','normalized',...
                        'Position',[.25,.80,.5,.1]);
                    
                DrinkText2 = uicontrol('Parent',Figure2,...
                        'Style','text',...
                        'String','You should drink',...
                        'Units','normalized',...
                        'Position',[.25,.70,.5,.1]);

                DrinkEdit = uicontrol('Parent',Figure2,...
                        'Units','normalized',...
                        'Position',[0.4,0.65,0.2,0.1]);
                        set(DrinkEdit, 'String', num2str(D));
                
                DrinkText3 = uicontrol('Parent',Figure2,...
                        'Style','text',...
                        'String','Oz. of Water a Day',...
                        'Units','normalized',...
                        'Position',[.25,.50,.5,.1]);
                    
                linkButton1 = uicontrol('Parent',Figure2,...
                'String','WATER FACTS',...
                'Units','normalized',...
                'Position',[0.38,0.35,0.25,0.1],...
                'callback',{@waterfactslink});
            
                linkButton2 = uicontrol('Parent',Panel3,...
                'String','BMI FACTS',...
                'Units','normalized',...
                'Position',[.38,.1,.25,.1],...
                'callback',{@linkCall});
            
                name = get(NameEdit,'String');
                his = get(HistoryEdit,'String');
                H = obj.history(his);
                save(get(NameEdit,'String'),'name','He','W','H')               
        end
        
        function WC_callback(hObject,eventdata)
            He = get(HeightEdit,'String');
            W = get(WeightEdit,'String');
            name = get(NameEdit,'String');
            if isempty(get(HistoryEdit,'String'))
                set(HistoryEdit,'String',0)
            end
            his = get(HistoryEdit,'String');
            H = obj.history(his);
            obj.History = H;
            P = obj.PBS(H);
            
            HisEdit = uicontrol('Parent',Panel2,...
                        'Units','normalized',...
                        'Position',[.38,.3,.25,.1]);
                        set(HisEdit, 'String', num2str(H));
                    
            PBSText = uicontrol('Parent',Panel4,...
                        'Style','text',...
                        'String','Plastic Bottles Saved:',...
                        'Units','normalized',...
                        'Position',[.25,.8,.5,.1]);

            PBSEdit = uicontrol('Parent',Panel4,...
                        'Units','normalized',...
                        'Position',[.38,.7,.25,.1]);
                        set(PBSEdit, 'String',num2str(P));
                        
            linkButton = uicontrol('Parent',Panel4,...
                'String','BOTTLED WATER FACTS',...
                'Units','normalized',...
                'Position',[0.25,0.35,0.5,0.1],...
                'callback',{@linkCallback});            
                        
            save(get(NameEdit,'String'),'name','He','W','H')
        end

        %Callback Functions
        function Load_callback(hObject,eventdata)
              l = (load(get(NameEdit,'String'),'name','He','W','H'));
              set(NameEdit,'String',l.name)
              set(HeightEdit,'String',l.He)
              set(WeightEdit,'String',l.W)
              obj.History = l.H;
        end
        
        function Coversion_callback(h,d)
            Figure3 = figure('Name','Units Calculator',...
                    'Units','normalized',...
                    'OuterPosition', [0.325 0.25 0.3 0.5]);

        % Creating different panels, Buttons and text boxes within the 
        % Units Calulator GUI figure                  
            FeetsText = uicontrol('Parent',Figure3,...
                        'Style','text',...
                        'String','Fts',...
                        'Units','normalized',...
                        'Position',[.15,.74,.2,.1]);

            FeetsEdit = uicontrol('Parent',Figure3,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[.2,.72,.1,.07]);
                    
            InchsText = uicontrol('Parent',Figure3,...
                        'Style','text',...
                        'String','Inches',...
                        'Units','normalized',...
                        'Position',[.3,.74,.2,.1]);

            InchsEdit = uicontrol('Parent',Figure3,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[.35,.72,.1,.07]);
                    
            MetersText = uicontrol('Parent',Figure3,...
                        'Style','text',...
                        'String','Meters',...
                        'Units','normalized',...
                        'Position',[.62,.74,.2,.1]);

            MetersEdit = uicontrol('Parent',Figure3,...
                        'Units','normalized',...
                        'Position',[.65,.72,.15,.07]);
                    
            KgsText = uicontrol('Parent',Figure3,...
                        'Style','text',...
                        'String','Kgs',...
                        'Units','normalized',...
                        'Position',[.2,.44,.2,.1]);

            KgsEdit = uicontrol('Parent',Figure3,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[.25,.42,.1,.07]);
                    
            lbssText = uicontrol('Parent',Figure3,...
                        'Style','text',...
                        'String','lbs',...
                        'Units','normalized',...
                        'Position',[.62,.44,.2,.1]);

            lbsEdit = uicontrol('Parent',Figure3,...
                        'Units','normalized',...
                        'Position',[.65,.42,.15,.07]);

            CalculateButton = uicontrol('Parent',Figure3,...
                         'Style','pushbutton',...
                         'String', 'Calculate',...
                         'Units','normalized',...
                         'Position', [0.4,0.2,.2,.08],...
                         'Callback',@calculate_callback);
                     
        function calculate_callback(h,d)
              I = get(InchsEdit,'String');
              F = get(FeetsEdit,'String');
              K = get(KgsEdit,'String');
              if isempty(get(FeetsEdit,'String'))
                  F = num2str(0);
              end
              
              M = obj.Meters(F,I);
              set(MetersEdit, 'String', num2str(M));
              
              L = obj.Lbs(K);
              set(lbsEdit, 'String', num2str(L));
            end
        end
          
        function waterfactslink(h,d)
                web('http://www.allaboutwater.org/water-facts.html') 
        end
        
        function linkCallback(h,d)
                web('https://www.banthebottle.net/bottled-water-facts/');
        end
        
        function linkCall(h,d)
                web('http://www.encyclopedia.com/medicine/anatomy-and-physiology/anatomy-and-physiology/body-mass-index')
        end
        
        end
    end
end

